---
CONVERT:
  PATHS: []
  DELETE_INPUT: false
  FPS_FROM_FILENAME: true
  INPUT_FPS: 20.0
  ROTATION: 0
  OVERWRITE: true

DETECT:
  PATHS: []
  FORCE_RELOAD_TORCH_HUB_CACHE: false
  HALF_PRECISION: false
  OVERWRITE: true
  YOLO:
    CONF: 0.25
    IMGSIZE: 640
    IOU: 0.45
    WEIGHTS: yolov8s

TRACK:
  PATHS: []
  IOU:
    SIGMA_H: 0.42
    SIGMA_IOU: 0.38
    SIGMA_L: 0.27
    T_MIN: 5
    T_MISS_MAX: 51
  OVERWRITE: true

LOG:
  LOG_LEVEL_CONSOLE: WARNING
  LOG_LEVEL_FILE: DEBUG
