---
PATHS: []

CONVERT:
  DEBUG: false
  DELETE_INPUT: false
  FPS_FROM_FILENAME: true
  INPUT_FPS: 20.0
  OUTPUT_FILETYPE: .mp4
  OUTPUT_FPS: 20.0
  OVERWRITE: true

DEFAULT_FILETYPE:
  DETECT: .otdet
  IMG: .jpg
  REFPTS: .otrfpts
  TRACK: .ottrk
  VID: .mp4

DETECT:
  DEBUG: false
  FORCE_RELOAD_TORCH_HUB_CACHE: false
  HALF_PRECISION: false
  OVERWRITE: true
  YOLO:
    CHUNKSIZE: 1
    CONF: 0.25
    IMGSIZE: 640
    IOU: 0.45
    NORMALIZED: false
    WEIGHTS: yolov5m

FILETYPES:
  DETECT:
    - .otdet
  IMG:
    - .jpg
    - .jpeg
    - .png
  REFPTS:
    - .otrfpts
  TRACK:
    - .ottrk
  TRANSFORM:
    - .gpkg
  VID:
    - .avi
    - .mkv
    - .m4v
    - .mov
    - .mp4
    - .mpg
    - .mpeg
    - .wmv

SEARCH_SUBDIRS: true

TRACK:
  DEBUG: false
  IOU:
    SIGMA_H: 0.42
    SIGMA_IOU: 0.38
    SIGMA_L: 0.27
    T_MIN: 5
    T_MISS_MAX: 51
  OVERWRITE: true

TRANSFORM:
  DEBUG: false
  OVERWRITE: true

UNDISTORT:
  DEBUG: false
  OVERWRITE: false
